development:
  adapter: sqlite3
  pool: 5
  database: db/development.sqlite3

# development:
#   adapter: postgresql
#   encoding: unicode
#   database: portacrana_development
#   pool: 5
#   host: localhost
